apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      # Spec fields that users can provide.
      name: string

  # Define the resources this API will manage.
  resources:
    - id: createNamespace
      template:
        apiVersion: kro.run/v1alpha1
        kind: Namespace
        metadata:
          name: ${schema.spec.name}-ns
        spec:
          name: ${schema.spec.name}
    - id: createConfigmap
      template:
        apiVersion: kro.run/v1alpha1
        kind: Configmap
        metadata:
          name: ${schema.spec.name}-config
        spec:
          name: ${schema.spec.name}