apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: sub-configmap
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RGD (create an instance).
  schema:
    apiVersion: v1alpha1
    kind: Configmap
    spec:
      # Spec fields that users can provide.
      name: string

  # Define the resources this API will manage.
  resources:
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.spec.name}-config
        data:
          appName: ${schema.spec.name}
          appVersion: "1.0.0"